### PR TITLE
changed icon class names, added new in fonts.css

### PR DESCRIPTION
**Pull request by sovrin**
icon names underwent some changes.
now they're more codiad oriented, easier to distinguish and a bit themeing friendlier.

also in "New File" in the contextmenu and "Settings" in the bottom left corner shared the same icon classname, so it was difficult to theme them appropriately.

*old classnames are kept for backwards compatibility with addons and other themes*

some examples:
icon-flashlight -> icon-password
icon-doc-text -> icon-new-file
icon-pen -> icon-rename

### CODE REVIEW

**Comment by sovrin** [comment]
I needed this to appropriately work on my current theme.
<https://github.com/sovrin/Codiad-Theme-Obsidian>
screen

**Comment by daeks** [comment]
My problem with that is, that other themes are also based on file icon and they will not work anymore. Secondly, there will be a breach between "before" and "after" this merge.

**Comment by sovrin** [comment]
How about default values which get overloaded by custom theme values if there are any?

**Comment by daeks** [comment]
I had a look about other entypo class names on google and we are following a very common line. 

Taking one "example":
"icon-lock" is known in other entypo namespaces also "..-lock". So the question which raises to me is, why should we do another nameing like the proposed "..-password"? 

From my personal feeling, I would like more to get rid of this font stuff and go back to svg drawings (sth like http://www.entypo.com/), which was also in discussion (https://github.com/Codiad/Codiad/issues/422#issuecomment-19008150) in the past.

**Comment by sovrin** [comment]
I see your point. But what I had in my mind with this change was, to give the dev the ability to change the icons in his theme more easily (like addressing it, where could it be located).

Your named lock example is one of the "minor" changes, is a thing of personal prefference and could be changed later if its necessary.
Changes like icon-doc-text -> icon-setting or icon-flashlight -> icon-password are these I thought could be helpfull.

It looses consistency if I change the content of the entypo classname with another font content. (thats what I did before the change)

You can close the pull request, if you want.
Probably I should ask/open an issue before I do such "drastic" changes like this generally.
I'm sorry, I'm fairly new to this whole git stuff :s

**Comment by daeks** [comment]
We have to keep in mind not to break old conventions as well. Nobody knows on which places with which customisations Codiad is running. Not everything is being public for us. 

The "lock" was only a small example, "doc-text" is quite another one (if you google it) ;-). I also understand your intention behind it, but as long as we are using a common iconbase (like entypo or fontawesome), I wouldn't want to break common namespace only for a project orientated behavior. This makes it also hard to maintain on updates. 

Absolutly no problem, thats why we are discussing it and . It always helps to have a look into the [contribution guide](https://github.com/Codiad/Codiad/blob/master/CONTRIBUTING.md). In the first lines, it is stated that you will save time if you open an issue *before* starting with it.

**Pull request closed without merging**
