### PR TITLE
Add print margin column as configurable property.

### PR DESCRIPTION
**Pull request by jackboespflug**
Adds the margin column as a configurable property.

### CODE REVIEW

**Comment by m4ddav3** [comment]
Pretty bad form to add all that whitespace largely in parts of the files that you haven't touched, let alone in the same commit as changes that are actually interesting #justsayin

**Comment by jackboespflug** [comment]
Agreed.  Will fix and try again.

**Comment by daeks** [comment]
thanks for your PR, as @m4ddav3 already mentioned it would be good to cleanup the whitespaces :)

**Comment by daeks** [comment]
closed cause of #918

**Pull request closed without merging**
