### PR TITLE
DirectoryDetails

### PR DESCRIPTION
**Pull request by atiris**
After the addition of the Slovak language, I found some untranslated parts. And it is not possible to change language for i18n string "Sync system settings on all devices" and next sentence. I really don't know why :(

Second part is about extended directory information when adding a new project.

### CODE REVIEW

**Comment by daeks** [comment]
These labels are just forgotten. Thanks for fixing them. Currently I would not like to merge that, as I do not prefer to post paths in the dialogs (looks awful + default should be always folder in workspace directory)

**Comment by atiris** [comment]
Ok. You find why i can not translate "Sync system settings on all devices" even if it is inside i18n method? https://github.com/Codiad/Codiad/blob/master/components/settings/settings.system.php#L34

(there is a "Filemanager Trigger" string, few lines up, which i can translate without any problems)

**Comment by daeks** [comment]
Oh havent seen the last comment. No, maybe it is too long.

**Comment by daeks** [comment]
Please reopen if there is any further change

**Pull request closed without merging**
