### PR TITLE
Creates tarballs using the Archive_Tar library

### PR DESCRIPTION
**Pull request by evertton**
A new solution to the issue #808 using the library `Archive_Tar`.

### CODE REVIEW

**Comment by daeks** [comment]
We can’t automatically merge this pull request. Please resolve conflicts before continuing.

**Comment by evertton** [comment]
Sorry, I should have documented the source.
http://pear.php.net/package/Archive_Tar

**Comment by daeks** [comment]
Hmm well I am not happy with that solution as not everybody has installed that. So it will require to install zip extension or this library or it will simply not work. If thats the case, then we can also stick with zip extension only

**Comment by evertton** [comment]
We can solve the dependency using Composer .
```json
"require": {
    "pear-pear/PEAR": "*",
    "pear/archive_tar": "*"
}
```
Or we can add the file [Archive/Tar.php](https://github.com/pear/Archive_Tar/blob/master/Archive/Tar.php) to `Codiad/lib`

**Comment by daeks** [comment]
at least we could add it to lib folder but generelly am not happy with third party implementations

**Comment by evertton** [comment]
I believe so gets better. :smile:

**Comment by daeks** [comment]
I am still not fine with it:

```
Warning: require_once(PEAR.php): failed to open stream: No such file or directory in \sandbox\817\lib\archive_tar.php on line 42

Fatal error: require_once(): Failed opening required 'PEAR.php' (include_path='.;\php\pear') in \sandbox\817\lib\archive_tar.php on line 42```

**Comment by evertton** [comment]
Since the objective is to reduce third-party dependencies...

**Comment by daeks** [comment]
Sry, if it is not working properly, I cant merge it

**Pull request closed without merging**
