### PR TITLE
Serbian translations

### PR DESCRIPTION
**Pull request by cobisimo**
Add serbian translations, added missing translations and login screen translation.

### CODE REVIEW

**Comment by daeks** [comment]
whats the reason for changing common.php?

**Comment by cobisimo** [comment]
The reason was to make global variable $lang available to set in config.php and set default language for login screen. Before, login screen was not translated at all.

**Comment by daeks** [comment]
well, if you want to have login screen translated as well, I would follow Codiad's guideline using a constant instead of a global variable in config.php

sth like:

define('LANGUAGE', 'en');

**Comment by cobisimo** [comment]
I agree that constants are better for this, but you already used global variable for this and I didn't wont to make a lot changes.
Also I noticed this line in common.php:
`145 $key = ucwords(strtolower($key)); //Test, test TeSt and tESt are exacly the same`
I don't know why you are doing all this conversions, I think that there is no need for this. If there is exact phrase do translation if not use original english phrase. Also I was thinking that we can make some auto populating for taking all string from code automatically to make easier translation.

**Comment by daeks** [comment]
I think you missunderstood me, I have nothing against the global variable $lang, but I wont like to have it in config.php. Therefore the definition of a default like language or theme should be done the same way. its not a very big change:

- add new constant LANGUAGE similar as THEME
https://github.com/Codiad/Codiad/blob/master/common.php#L64

- replace "en" with new CONSTANT
https://github.com/Codiad/Codiad/blob/master/common.php#L95

Regarding your mentioned line 145, I dont know neither as I have not written it. I am open for any usefull change.

**Comment by cobisimo** [comment]
Ok, I add constant LANGUAGE and simplify changes in common.php

**Pull request merged**
