### PR TITLE
Fixed: Marketplace search function.

### PR DESCRIPTION
**Pull request by paul1522**

### CODE REVIEW

**Comment by daeks** [comment]
What exactly does it fix?

**Comment by paulgeneres** [comment]
Doing a search for, for example, "git" will return no results. After committing the PR searching for "git" will return the correct results: "CodeGit" and "GitAdmin". The reason is that the `break` statement is terminating the `foreach` loop prematurely; right after the first mis-match which causes the rest of the array to be skipped. Replacing it with a `continue` statement allows the search to continue with the next element in the array.

**Comment by daeks** [comment]
Thanks that helped me a lot :)

**Comment by paulgeneres** [comment]
My pleasure, and thank you for all of the time and attention you have given to this project.

**Review by konarski007 — COMMENTED** [review]
Leave

**Pull request merged**
